version: "3"

services:
  web:
    container_name: web
    build:
      context: .
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=devpassword
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_BD=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpassword
